### ISSUE TITLE
move some scripts into special folders

### ISSUE THREAD

**Issue by rhelmot** [angr/angr-dev#12]
`tests` folder:

- `angr-test`
- `appveyor_test.bat`
- `lint.py`
- `test.sh`
- `travis-*.sh`

`admin` (?) folder:

- `bdist.bat`
- `bdist.sh`
- `prsync.py`
- `releaser.sh`

Of course this is gonna require updating links in a lot of places. The root is a little cluttered right now.

**Comment by zardus** [comment]
+1000

On Feb 9, 2017 1:58 AM, "Andrew Dutcher" <notifications@github.com> wrote:

tests folder:

   - angr-test
   - appveyor_test.bat
   - lint.py
   - test.sh
   - travis-*.sh

admin (?) folder:

   - bdist.bat
   - bdist.sh
   - prsync.py
   - releaser.sh

Of course this is gonna require updating links in a lot of places. The root
is a little cluttered right now.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angr/angr-dev/issues/12>, or mute the thread

**Comment by rhelmot** [comment]
Done :)
