### ISSUE TITLE
cvc4-solver dependency

### ISSUE THREAD

**Issue by sraboy** [angr/angr-dev#72]
https://github.com/angr/angr-dev/blob/9f95e8d4f0f55144e41c8828de11b71209ba3bc0/setup.sh#L495

Should `cvc4-solver` still be in here? It was removed here https://github.com/angr/claripy/commit/3a6c5ae99b514d12835b2a81fe0f891f390ece8d.

**Comment by zardus** [comment]
I guess this is a leftover from @Phat3. Seba, could you take a look?

**Comment by Phat3** [comment]
Yep is a leftover, we can remove it.

Although if we remove it some of the test cases about the java part will fail

**Comment by sraboy** [comment]
Just FYI, one of my coworkers was unable to install without removing this.
Pip complained about not finding an appropriate version, though I believe
he was using pip within a conda environment.

**Comment by rhelmot** [comment]
cvc4 is necessary for running tests. It is optional, so it should not be in the claripy reqs, but it is here so that our CI tests will run. The dep could potentially be added to another code path more specific to the CI installation. (this is perhaps the case for most of the weird-looking apt and pip deps)

**Comment by sraboy** [comment]
Gotcha, no problem. We got around it easy enough. Just thought it may have been an oversight. Feel free to close if there's no further action planned.
